# This starter workflow is for a CMake project running on a single platform. There is a different starter workflow if you need cross-platform coverage.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
name: CMake on a single platform

on:
  push:
    branches: [ "windows-workflow" ]
  pull_request:
    branches: [ "windows-workflow" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  GENERATOR: "Visual Studio 18 2026"
  OPENCV_VERSION: 5.0.0

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: windows-2025-vs2026

    steps:
    - uses: actions/checkout@v4

    - name: Install Qt
      shell: bash
      run: |
        curl -L https://github.com/miurahr/aqtinstall/releases/download/v3.3.0/aqt.exe -o aqt.exe
        ./aqt.exe install-qt windows desktop 6.8.3 win64_msvc2022_64

    - name: Install OpenCV
      shell: bash
      run: |
        git clone https://github.com/opencv/opencv.git
        git clone https://github.com/opencv/opencv_contrib.git
        cd opencv
        git reset --hard ${{env.OPENCV_VERSION}}
        cd ..
        cd opencv_contrib
        git reset --hard ${{env.OPENCV_VERSION}}
        cd ..
        mkdir only_img_hash_module
        cp -r opencv_contrib/modules/img_hash only_img_hash_module
        cd opencv
        mkdir build
        cd build
        cmake -G ${{env.GENERATOR}} -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DBUILD_opencv_world=OFF -DBUILD_LIST=img_hash,videoio,imgcodecs -DBUILD_PERF_TESTS=OFF -DBUILD_TESTS=OFF -DBUILD_DOCS=OFF -DWITH_CUDA=OFF -DBUILD_EXAMPLES=OFF -DINSTALL_CREATE_DISTRIB=ON -DOPENCV_EXTRA_MODULES_PATH=../../only_img_hash_module -DCMAKE_INSTALL_PREFIX=../../install/opencv ..
        cmake --build . --config ${{env.BUILD_TYPE}}
        cmake --build . --target install --config ${{env.BUILD_TYPE}}

    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: cmake -G ${{env.GENERATOR}} -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_PREFIX_PATH="${{github.workspace}}/6.8.3/msvc2022_64/lib/cmake;${{github.workspace}}/install/opencv"

    - name: Build
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
